---
permalink: task-restore-virtual-machines-from-amazon-fsx.html 
sidebar: sidebar 
keywords: restore, virtual machines, amazon fsx 
summary: 仮想マシンをリストアするときに、選択したバックアップコピーで既存の内容を上書きするか、仮想マシンのコピーを作成できます。 
---
= Amazon FSxから仮想マシンをリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンをリストアするときに、選択したバックアップコピーで既存の内容を上書きするか、仮想マシンのコピーを作成できます。

.作業を開始する前に
* バックアップが存在している必要があります。
+
仮想マシンをリストアする前に、BlueXPのVMのバックアップとリカバリを使用して仮想マシンのバックアップを作成しておく必要があります。

+
[NOTE]
====
BlueXPのVMのバックアップとリカバリ以外のソフトウェアで実行された仮想マシンのSnapshotコピーがあると、リストア処理を正常に完了できません。

====
* 仮想マシンは転送中ではありません。
+
リストアする仮想マシンがvMotionまたはStorage vMotionの状態でないことを確認します。

* HA構成エラー。
+
バックアップを別の場所にリストアする前に、 vCenter ESXi Host Summary 画面に HA 構成のエラーが表示されていないことを確認します。



.このタスクについて
* 仮想マシンの登録が解除され、再登録されました。
+
仮想マシンのリストア処理を実行すると、元の仮想マシンの登録が解除され、バックアップSnapshotコピーから仮想マシンがリストアされ、リストアされた仮想マシンが同じESXiサーバに登録されます。リストア後に、仮想マシンをリソースグループに手動で追加する必要があります。

* データストアのリストア
+
データストアはリストアできませんが、データストア内の任意の仮想マシンをリストアできます。

* 仮想マシンのVMware整合性スナップショットの失敗。
+
仮想マシンのVMware整合性スナップショットに障害が発生した場合でも、仮想マシンはバックアップされます。バックアップコピーに格納されたエンティティは、リストアウィザードで表示し、リストア処理に使用できます。



.手順
. VMware vSphere Web Client GUIで、ツールバーの*[メニュー]*をクリックし、*[インベントリ]*をクリックして*[仮想マシンおよびテンプレート]*を選択します。
. 左側のナビゲーションペインで、*[仮想マシン]*を右クリックし、ドロップダウンリストから*[Cloud NetApp Backup]*を選択し、*[リストア]*を選択してウィザードを開始します。
. リストア * ウィザードの * バックアップの選択 * ページで、リストアするバックアップ Snapshot コピーを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、フィルタアイコンをクリックして日時の範囲、 VMware スナップショットの有無、マウントするバックアップの有無、および場所を選択して、バックアップリストをフィルタリングすることができます。[OK] をクリックしてウィザードに戻ります。

. [Select Scope]ページで、[Restore scope]フィールドで*[Entire Virtual Machine]*を選択し、リストア先を選択してから、バックアップをマウントするデスティネーションESXiの情報を入力します。
+
パーシャル・バックアップをリストアする場合、リストア処理では * Select Scope * ページがスキップされます。

. リストア処理後に仮想マシンの電源をオンにする場合は、[* Restart VM]*チェックボックスを有効にします。
. [ * 場所の選択 * ] ページで、リストアしたデータストアの場所を選択します。
. [概要]*ページを確認し、*[完了]*をクリックします。
. *オプション*：画面下部の*[最近のタスク]*をクリックして、処理の進捗状況を監視します。


.完了後
* リストアした仮想マシンをリソースグループに追加します。
+
仮想マシンはリストアされますが、以前のリソースグループに自動的に追加されることはありません。そのため、リストアした仮想マシンを適切なリソースグループに手動で追加する必要があります。


