---
permalink: task-download-the-open-virtual-appliance.html 
sidebar: sidebar 
keywords: download, open virtual appliance 
summary: VMware vCenter 8.0以降でOpen Virtual Appliance（OVA）をダウンロードして、VMのBlueXPバックアップおよびリカバリを導入します。 
---
= Open Virtual Applianceのダウンロード
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vCenter 8.0以降でOpen Virtual Appliance（OVA）をダウンロードして、VMのBlueXPバックアップおよびリカバリを導入します。

.作業を開始する前に
Entrust証明書によって署名されたOVAが信頼されていない場合は、中間証明書をインストールしてvCenterに追加してください。

.手順
. VMS OVAのBlueXPバックアップ/リカバリをダウンロードするには、次の手順を実行します。
+
.. にログインします https://mysupport.netapp.com/products/index.html["NetApp Support Site"^]
.. 製品のリストから* BlueXP Backup and Recovery for VMs *を選択し、*[Download Latest Release]*ボタンをクリックします。
.. BlueXPのVMのバックアップとリカバリをダウンロードします `.tar` 任意の場所にファイルを移動します。


. tarファイルの内容を展開します。tarファイルには、ovaフォルダとcertsフォルダが含まれています。certsフォルダには中間証明書が含まれています。
. vSphere Clientで、*[管理]>[証明書]>[証明書管理]*に移動します。
. [信頼されたルート証明書]*の横にある*[追加]*をクリックします。
+

NOTE: デフォルトでは、ルート証明書がインストールされています。

+
.. certsフォルダに移動します。
.. 中間証明書を選択します。
.. 各証明書を一度に1つずつインストールします。


. 証明書は、[信頼されたルート証明書]の下のパネルに追加されます。
+
証明書をインストールすると、OVAを検証して導入できます。



[NOTE]
====
ダウンロードしたOVAが改ざんされていない場合は、[Publisher]列に[Trusted certificate]と表示されます。

====