---
permalink: task-deploy-bluexp-backup-and-recovery-for-vms.html 
sidebar: sidebar 
keywords: deploy, bluexp, backup, recovery for VMs 
summary: 仮想マシン上のVM、データストア、アプリケーションと整合性のあるデータベースを保護するには、VMに対してBlueXPのバックアップとリカバリを導入する必要があります。 
---
= BlueXPでVMのバックアップとリカバリを導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンのVMとデータストアを保護するには、VMに対してBlueXPのバックアップとリカバリを導入する必要があります。

.作業を開始する前に
+++++

[NOTE]
====
OVA環境は、VMware vCenter 8.0以降でサポートされます。

====
* 導入の要件を確認しておく必要があります。
* AWSでサポートされているバージョンのVMCが実行されている必要があります。
* VMC on AWS環境の設定とセットアップが完了している必要があります。
* VMのBlueXPのバックアップとリカバリ用のESXiホストをセットアップしておく必要があります。
* VMのBlueXPバックアップとリカバリをダウンロードしておく必要があります `.tar` ファイル。
* VMC on AWSインスタンスのログイン認証の詳細を確認しておく必要があります。
* 有効な公開鍵ファイルと秘密鍵ファイルがある証明書が必要です。詳細については、「ストレージ証明書管理」セクションの記事を参照してください。
* vSphere Clientのすべてのブラウザセッションからログアウトして閉じておく必要があります。また、VMのBlueXPバックアップおよびリカバリの導入時にブラウザキャッシュ問題が発生しないように、ブラウザキャッシュを削除しておく必要があります。
* vCenter で Transport Layer Security （ TLS ）を有効にしておく必要があります。VMware のドキュメントを参照してください。
* vCenterと同じタイムゾーンのVMについて、BlueXPのバックアップとリカバリを導入しておく必要があります。


.手順
. VMware vCenter 7.0.3以降のバージョンの場合は、「Open Virtual Appliance（OVA）のダウンロード」セクションの手順に従って、証明書をvCenterにインポートします。
. ブラウザから VMware vSphere vCenter にアクセスします。
. VMware vCenter Single Sign-Onページにログインします。
. Navigator ペインで、データセンター、クラスタ、ホストなどの仮想マシンの有効な親オブジェクトであるインベントリオブジェクトを右クリックし、 * Deploy OVF Template * を選択して VMware Deploy ウィザードを起動します。
. を展開します `.tar` を含むファイル `.ova` ファイルをローカルシステムに保存します。[Select an OVF template]ページで、の場所を指定します `.ova` 内のファイル `.tar` 展開されたフォルダ。
. 「 * 次へ * 」をクリックします。
. [ 名前とフォルダの選択 * ] ページで、 VM または vApp の一意の名前を入力し、導入場所を選択して、 [ 次へ * ] をクリックします。
+
このステップでは、をインポートする場所を指定します `.ova` vCenterにファイルを移動します。VMのデフォルト名は、選択したの名前と同じです `.ova` ファイル。デフォルト名を変更した場合は、各VMC on AWS VMフォルダ内で一意の名前を選択します。

+
VM のデフォルトの導入場所は、ウィザードを開始したインベントリオブジェクトです。

. [ リソースの選択 *] ページで、導入した VM テンプレートを実行するリソースを選択し、 [ 次へ *] をクリックします。
. [* Review details（レビューの詳細）]ページで、を確認します `.ova` テンプレートの詳細を入力し、[次へ]をクリックします。
. [ ライセンス契約 * ] ページで、 [ すべてのライセンス契約に同意します ] のチェックボックスをオンにします。 *
. ［ * ストレージの選択 * ］ ページで、導入した OVF テンプレートのファイルの保存場所と保存方法を定義します。
+
.. VMDK のディスク形式を選択します。
.. VM ストレージポリシーを選択します。
+
このオプションは、デスティネーションリソースでストレージポリシーが有効になっている場合にのみ使用できます。

.. 導入した OVA テンプレートを保存するデータストアを選択します。
+
構成ファイルと仮想ディスクファイルはデータストアに格納されます。

+
仮想マシンまたは vApp および関連するすべての仮想ディスクファイルを格納できる十分な大きさのデータストアを選択してください。



. [ ネットワークの選択 *] ページで、次の操作を行います。
+
.. 送信元ネットワークを選択し、宛先ネットワークにマッピングします。
+
ソースネットワーク列には、 OVA テンプレートで定義されたすべてのネットワークが表示されます。

.. [IP Allocation Settings] セクションで、必要な IP プロトコルを選択し、 [*Next] をクリックします。
+
BlueXPのVMのバックアップとリカバリでは、1つのネットワークインターフェイスがサポートされます。複数のネットワークアダプタが必要な場合は、手動でセットアップする必要があります。



. [ テンプレートのカスタマイズ ] ページで、次の操作を行います。
+
.. [* Register to Existing vCenter* （既存の vCenter に登録） ] セクションで、仮想アプライアンスの vCenter 名と vCenter クレデンシャルを入力します。
+
vCenter username *フィールドに、domain\usernameの形式でユーザ名を入力します。

.. [Create BlueXP backup and recovery for VMs credentials]*セクションで、ローカルクレデンシャルを入力します。
+
[*Username*] フィールドに、ローカルユーザ名を入力します。ドメインの詳細は入力しないでください。

+
[IMPORTANT]
====
指定するユーザ名とパスワードを書き留めます。あとでVMのBlueXPのバックアップとリカバリの設定を変更する場合は、これらのクレデンシャルを使用する必要があります。

====
.. maintユーザのクレデンシャルを入力します。
.. [ ネットワークプロパティの設定 *] に、ホスト名を入力します。
+
... [*IPv4 ネットワークプロパティの設定 *] セクションで、 IPv4 アドレス、 IPv4 ネットマスク、 IPv4 ゲートウェイ、 IPv4 プライマリ DNS 、 IPv4 セカンダリ DNS などのネットワーク情報を入力します。 および IPv4 検索ドメインを使用できます。
+
[IMPORTANT]
====
ネットワーク構成としてDHCPを使用する場合は、これらの手順を省略し、[Setup Network Properties]セクションのエントリを空白のままにしておくことができます。

====


.. * Setup Date and Time * で、 vCenter が配置されているタイムゾーンを選択します。


. [ 完了準備完了 ] ページでページを確認し、 [ 完了 ] をクリックします。
+
すべてのホストに IP アドレスが設定されている必要があります（ FQDN ホスト名はサポートされません）。展開操作では、展開前に入力が検証されません。

+
OVF のインポートおよび導入タスクが完了するまでの間、 Recent Tasks ウィンドウで導入の進捗状況を確認できます。

+
BlueXPのVMのバックアップとリカバリの導入が完了すると、Linux VMとして導入されてvCenterに登録され、VMware vSphere Clientがインストールされます。

. BlueXPのVMのバックアップとリカバリを導入したVMに移動し、*[概要]*タブをクリックし、*[電源をオン]*ボックスをクリックして仮想アプライアンスを起動します。
. VMのBlueXPバックアップ/リカバリの起動中に、導入したBlueXPのVMバックアップ/リカバリを右クリックし、*[ゲストOS ]*を選択して*[VMwareツールのインストール]*をクリックします。

